var GAME_LEVELS = [
  /*["  x                                                                          x  ",
   "  x                                           c           c                ccx  ",
   "  x                                     c           c           c          ccx  ",
   "  x                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x  ",
   "  x                       x                                                  x  ",
   "  x                                                                          x  ",
   "  x                   x                                                      x  ",
   "  x                        c                                                 x  ",
   "  x                      xxxxx   x                                           x  ",
   "  x                                                                          x  ",
   "  x                                 x                                        x  ",
   "  x                                                                          x  ",
   "  x                                     x                                    x  ",
   "  x                                                                          x  ",
   "  x                                 x       x                            c   x  ",
   "  x                                                                     xxx  x  ",
   "  x     @                  c     xx    xx        xx                     x x  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            xxxxxxxxxxxxxx xxxx  ",
   "                              x                        x   x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                "],*/
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x        x  c                            x                                x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!v!x",
   "x        x                               x c                            c x      x!!!!!!!!!!!!v!!!v!!!!v!!!!!!! !x",
   "x                    xxxxxxxxxx          x       @       x            xxxxx      xxvxxxxxvvxxx xxx xxxx xxxxvxx xx",
   "x                  xxx                   x       x x     x                                                       x",
   "x          x   x     x                   x         x     x         x                                             x",
   "xxxxxxxxxx!!!!!!!!!!!xc                  x   x     x     x                                                       x",
   "x       cxxxxxxxxxxxxx              x  c x       x x     x      xx                                               x",
   "x                        xxx x  x      x x         x           xx!x                             c                x",
   "x   xxx                 x!!!!!!!!!!!!!!!!x    x   cx            x!!x                                             x",
   "x   xvxxxxxxxxxxxxxxxxxxxvxxvxxvxvvxxxxxxx       xxx         x  x!!!x          x     s                         c x",
   "x                                           xxx    x!!!xx       x!!!!x            xxxx       x    x      x   xxxxx",
   "x                                          xx!!!!!!x!!!!x  x    x!!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x                                         xxx!!!!!!xxxxxx!!x!!!!x!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                 c                                                                            ",
   "    c                                                                                                         ",
   "           xxxxxx  xxxxxxxxxxxxx  xxxxxxxxxxx   xxxxxxxxx                                                     ",
   "      x                                                                                                       ",
   "                                                                                                              ",
   "        x                                                                                                     ",
   "                                                                                                              ",
   "            x                                                                                                 ",
   "                x                                                                                             ",
   "                            x                                                                                 ",
   "                   x                                                                                          ",
   "                       x        x                                                                             ",
   "                                    x                                                                         ",
   "                                                                                                              ",
   "                                        x   x                                                                 ",
   "                                                     c                                                        ",
   "                                          c     xxxxxx          x   x       c                                 ",
   "                                                                                                              ",
   "                                        x   x                            x     x!!x                           ",
   "                                                                               x!!x                           ",
   "                                    x                                          x!!x                           ",
   "                   x                                            c              x!x                            ",
   "                            x   x                                              xxc                            ",
   "               x        x                                                       x     s                       ",
   "       x   x                                                      x    x        x    xxx      x      x        ",
   "x     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           !!!!!!!!!!!!!!!!!x        ",
   "x    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x!!!!!!!!!!!!!!!!!!x       ",
   "x @ x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!!x   c  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["x                        x",
   "x           x            x",
   "x                        x",
   "x     ccccccccccccc      x",
   "x           c            x",
   "x           c            x",
   "x           c            x",
   "x           c            x",
   "x           c            x",
   "x           c            x",
   "x                        x",
   "x     c           c      x",
   "x     c           c      x",
   "x     c           c      x",
   "x     ccccccccccccc      x",
   "x     c           c      x",
   "x     c           c      x",
   "x     c           c      x",
   "x                        x",
   "x     ccccccccccccc      x",
   "x     c                  x",
   "x     c                  x",
   "x     cccccccccc         x",
   "x     c                  x",
   "x     c                  x",
   "x     ccccccccccccc      x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x     ccccccccccccc      x",
   "x     c                  x",
   "x     c                  x",
   "x     cccccccccc         x",
   "x     c                  x",
   "x     c                  x",
   "x     ccccccccccccc      x",
   "x                        x",
   "x     cc          c      x",
   "x     c  c        c      x",
   "x     c    c      c      x",
   "x     c     c     c      x",
   "x     c      c    c      x",
   "x     c        c  c      x",
   "x     c          cc      x",
   "x                        x",
   "x     cccccccccc         x",
   "x     c         c        x",
   "x     c          c       x",
   "x     c           c      x",
   "x     c          c       x",
   "x     c         c        x",
   "x     cccccccccc         x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x                        x",
   "x                        x",
   "xs                      sx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
